// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBexFQJ5ejdnkhCdeEFp-Ja-7qh7lF53_Y',
    appId: '1:437436814903:web:c0f25b370ae545681391b2',
    messagingSenderId: '437436814903',
    projectId: 'duan-4904c',
    authDomain: 'duan-4904c.firebaseapp.com',
    storageBucket: 'duan-4904c.appspot.com',
    measurementId: 'G-NT3171KZEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4qtCRdtPxWiLrpR3cu8je13yHuawFgdY',
    appId: '1:437436814903:android:f9ca08ec641b9b301391b2',
    messagingSenderId: '437436814903',
    projectId: 'duan-4904c',
    storageBucket: 'duan-4904c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsnd52Hry_8qTa12kxLIGpNjIKoMmbXSQ',
    appId: '1:437436814903:ios:2813f9289e57731f1391b2',
    messagingSenderId: '437436814903',
    projectId: 'duan-4904c',
    storageBucket: 'duan-4904c.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsnd52Hry_8qTa12kxLIGpNjIKoMmbXSQ',
    appId: '1:437436814903:ios:5b66a4d529c48ec61391b2',
    messagingSenderId: '437436814903',
    projectId: 'duan-4904c',
    storageBucket: 'duan-4904c.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
